name: CI

on:
  pull_request:
    types: [review_requested, ready_for_review]

  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0"

jobs:
  test-on-nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: diku-dk/install-futhark@v1.1.0
      with:
        version: 'nightly'

    - run: futhark pkg sync
    
    - run: futhark test --pass-compiler-option=--Werror lib/github.com/diku-dk/containers/*_test.fut